use_default_settings: true
server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "jp-ai-change-this-key"
  limiter: false
search:
  safe_search: 0
  formats: [html, json]
redis:
  url: redis://valkey:6379/0
